### ISSUE TITLE
MSK välja projekt i projektlistan

### ISSUE THREAD

**Issue by ulrika-mansson** [Problemil/KANBAN#4]
då visas alla kort som hör till projektet i de fyra kolumnerna

**Comment by Problemil** [comment]
Jag ska göra så att så att om jag klickar på projekt 1 kommer sakerna där synas, projekt två då döljs projekt 1 och projekt 2 visas och samma sak med projekt 3 & 4. Typ!

-Göra så att välja/visa projekt.
-radioknappar
-googla
