### ISSUE TITLE
MSK skapa issue-kort till projekt och lägga i kolumner

### ISSUE THREAD

**Issue by ulrika-mansson** [Problemil/KANBAN#5]

**Comment by ulrika-mansson** [comment]
knapp "Skapa issue"
det ska finnas en knapp till varje kolumn (4 st.)

**Comment by Andreeez** [comment]
- Namn på ansvarig ska stå på kortet 
- Vad för uppgift
- Man ska kunna flytta kortet till de olika kolumner
-

**Comment by ulrika-mansson** [comment]
klart
